version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: tryon-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: tryon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # Útil no front para chamar o backend via rede do compose
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"
    restart: unless-stopped
